blank_issues_enabled: false
contact_links:
  - name: "\U0001F4AC General Question"
    url: "https://github.com/microsoft/m365-agent-templates/discussions"
    about: "Ask questions and share ideas in GitHub Discussions"
